# Phase 4 — Color assignment: color_branches()
# Reference: Python plotly create_dendrogram() JSON fixtures (tiny4 dataset).
# Gate: cluster count agreement with Python; edge-case coloring is correct.
#
# Fixtures are pre-generated by tests/testthat/fixtures/generate_fixtures.py.
# If the JSON files are absent (Python plotly not yet run), the fixture-
# dependent tests are skipped automatically.

fixture_path <- testthat::test_path("fixtures")

has_fixture <- function(name) {
  file.exists(file.path(fixture_path, name))
}

# --- Structure -----------------------------------------------------------

test_that("color_branches() returns a data.frame", {
  hc   <- hclust_complete(dist(tiny4))
  segs <- extract_segments(hc)
  out  <- color_branches(segs, hc)
  expect_s3_class(out, "data.frame")
})

test_that("color_branches() preserves all original columns", {
  hc   <- hclust_complete(dist(tiny4))
  segs <- extract_segments(hc)
  out  <- color_branches(segs, hc)
  expect_true(all(c("x", "y", "xend", "yend") %in% names(out)))
})

test_that("color_branches() adds a 'color' column", {
  hc   <- hclust_complete(dist(tiny4))
  segs <- extract_segments(hc)
  out  <- color_branches(segs, hc)
  expect_true("color" %in% names(out))
})

test_that("color_branches() returns one color per segment row", {
  hc   <- hclust_complete(dist(tiny4))
  segs <- extract_segments(hc)
  out  <- color_branches(segs, hc)
  expect_equal(nrow(out), nrow(segs))
})

test_that("color_branches() colors are non-empty character strings", {
  hc   <- hclust_complete(dist(medium))
  segs <- extract_segments(hc)
  out  <- color_branches(segs, hc)
  expect_type(out$color, "character")
  expect_true(all(nchar(out$color) > 0))
})

# --- color_threshold = NULL: all segments the same color ----------------

test_that("color_threshold=NULL produces a single color (all above threshold)", {
  hc   <- hclust_complete(dist(tiny4))
  segs <- extract_segments(hc)
  out  <- color_branches(segs, hc, color_threshold = NULL)
  expect_length(unique(out$color), 1L)
})

# --- color_threshold = 0: every leaf cluster gets its own color ----------

test_that("color_threshold=0 produces N distinct colors (one per leaf)", {
  hc   <- hclust_complete(dist(tiny4))
  segs <- extract_segments(hc)
  out  <- color_branches(segs, hc, color_threshold = 0)
  # Every leaf is its own cluster → number of distinct colors == N leaves
  expect_gte(length(unique(out$color)), nrow(tiny4))
})

# --- color_threshold very high: all in one cluster → single color --------

test_that("color_threshold above max height produces a single color", {
  hc    <- hclust_complete(dist(tiny4))
  segs  <- extract_segments(hc)
  above <- max(hc$height) + 100
  out   <- color_branches(segs, hc, color_threshold = above)
  expect_length(unique(out$color), 1L)
})

# --- Default palette matches Python plotly's 8 colors -------------------

test_that("default colorscale contains 8 entries matching Python plotly palette", {
  cs <- default_colorscale()
  expect_length(cs, 8L)
  expect_equal(cs[[1]], "rgb(0,116,217)")    # blue
  expect_equal(cs[[8]], "rgb(255,220,0)")    # yellow
})

# --- Custom colorscale ---------------------------------------------------

test_that("custom colorscale colors appear in output", {
  hc  <- hclust_complete(dist(medium))
  segs <- extract_segments(hc)
  custom <- c("red", "blue", "green", "yellow", "purple", "orange", "black", "white")
  out <- color_branches(segs, hc, color_threshold = 50, colorscale = custom)
  expect_true(all(out$color %in% custom))
})

# --- Python fixture: cluster count agreement ----------------------------

test_that("cluster count matches Python fixture [tiny4, threshold=2]", {
  skip_if_not(has_fixture("tiny4_thresh_2.json"),
              "Python fixture tiny4_thresh_2.json not yet generated")
  skip_if_not_installed("jsonlite")

  ref     <- jsonlite::fromJSON(file.path(fixture_path, "tiny4_thresh_2.json"))
  ref_n   <- length(unique(sapply(ref, `[[`, "color")))

  hc      <- hclust_complete(dist(tiny4))
  segs    <- extract_segments(hc)
  out     <- color_branches(segs, hc, color_threshold = 2)
  our_n   <- length(unique(out$color))

  expect_equal(our_n, ref_n)
})

test_that("cluster count matches Python fixture [tiny4, threshold=NULL]", {
  skip_if_not(has_fixture("tiny4_thresh_NULL.json"),
              "Python fixture tiny4_thresh_NULL.json not yet generated")
  skip_if_not_installed("jsonlite")

  ref   <- jsonlite::fromJSON(file.path(fixture_path, "tiny4_thresh_NULL.json"))
  ref_n <- length(unique(sapply(ref, `[[`, "color")))

  hc    <- hclust_complete(dist(tiny4))
  segs  <- extract_segments(hc)
  out   <- color_branches(segs, hc, color_threshold = NULL)
  expect_equal(length(unique(out$color)), ref_n)
})

test_that("cluster count matches Python fixture [tiny4, threshold=999]", {
  skip_if_not(has_fixture("tiny4_thresh_999.json"),
              "Python fixture tiny4_thresh_999.json not yet generated")
  skip_if_not_installed("jsonlite")

  ref   <- jsonlite::fromJSON(file.path(fixture_path, "tiny4_thresh_999.json"))
  ref_n <- length(unique(sapply(ref, `[[`, "color")))

  hc    <- hclust_complete(dist(tiny4))
  segs  <- extract_segments(hc)
  out   <- color_branches(segs, hc, color_threshold = 999)
  expect_equal(length(unique(out$color)), ref_n)
})
