// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_hclust_geometry
List cpp_hclust_geometry(IntegerMatrix merge, NumericVector height, IntegerVector order, CharacterVector labels, double leaf_drop, bool need_nodes);
RcppExport SEXP _plotly_dendro_cpp_hclust_geometry(SEXP mergeSEXP, SEXP heightSEXP, SEXP orderSEXP, SEXP labelsSEXP, SEXP leaf_dropSEXP, SEXP need_nodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type merge(mergeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type height(heightSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type order(orderSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< double >::type leaf_drop(leaf_dropSEXP);
    Rcpp::traits::input_parameter< bool >::type need_nodes(need_nodesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hclust_geometry(merge, height, order, labels, leaf_drop, need_nodes));
    return rcpp_result_gen;
END_RCPP
}
// node_table
DataFrame node_table(IntegerMatrix merge, NumericVector height, IntegerVector order);
RcppExport SEXP _plotly_dendro_node_table(SEXP mergeSEXP, SEXP heightSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type merge(mergeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type height(heightSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type order(orderSEXP);
    rcpp_result_gen = Rcpp::wrap(node_table(merge, height, order));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hclust_branch_ids
Nullable<IntegerVector> cpp_hclust_branch_ids(IntegerMatrix merge, NumericVector height, IntegerVector order, NumericVector segment_x, NumericVector segment_y, NumericVector segment_xend, NumericVector segment_yend, IntegerVector leaf_color_ids);
RcppExport SEXP _plotly_dendro_cpp_hclust_branch_ids(SEXP mergeSEXP, SEXP heightSEXP, SEXP orderSEXP, SEXP segment_xSEXP, SEXP segment_ySEXP, SEXP segment_xendSEXP, SEXP segment_yendSEXP, SEXP leaf_color_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type merge(mergeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type height(heightSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type order(orderSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type segment_x(segment_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type segment_y(segment_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type segment_xend(segment_xendSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type segment_yend(segment_yendSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type leaf_color_ids(leaf_color_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hclust_branch_ids(merge, height, order, segment_x, segment_y, segment_xend, segment_yend, leaf_color_ids));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_plotly_dendro_cpp_hclust_geometry", (DL_FUNC) &_plotly_dendro_cpp_hclust_geometry, 6},
    {"_plotly_dendro_node_table", (DL_FUNC) &_plotly_dendro_node_table, 3},
    {"_plotly_dendro_cpp_hclust_branch_ids", (DL_FUNC) &_plotly_dendro_cpp_hclust_branch_ids, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_plotly_dendro(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
