# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_hclust_geometry <- function(merge, height, order, labels, leaf_drop, need_nodes) {
    .Call(`_plotly_dendro_cpp_hclust_geometry`, merge, height, order, labels, leaf_drop, need_nodes)
}

cpp_hclust_branch_ids <- function(merge, height, order, segment_x, segment_y, segment_xend, segment_yend, leaf_color_ids) {
    .Call(`_plotly_dendro_cpp_hclust_branch_ids`, merge, height, order, segment_x, segment_y, segment_xend, segment_yend, leaf_color_ids)
}

